package educatus.shared.request;

public enum RequestTypeEnum {
	MAIN_MENU_CONTENT_REQUEST,
	FOOTER_CONTENT_REQUEST,
	
	HOME_PAGE_CONTENT_REQUEST,
	SEMINARY_MAIN_PAGE_CONTENT_REQUEST,
	SEMINARY_EDITOR_CONTENT_REQUEST,
	SEMINARY_VIEWER_CONTENT_REQUEST,
	PROFIL_PAGE_CONTENT_REQUEST
}
