package educatus.server.businesslogic.uibuilder;

import com.google.inject.Inject;
import com.google.inject.Singleton;

import educatus.server.persist.dao.SeminaryDao;
import educatus.server.persist.dao.seminary.Category;
import educatus.shared.dto.seminary.CategoryCoreContent;
import educatus.shared.dto.seminary.SeminaryCoreContent;
import educatus.shared.dto.seminary.SeminaryHomeListingContent;

@Singleton
public class SeminaryHomeListingFactory {
	
	@Inject
	private SeminaryDao semDao;
	
	public SeminaryHomeListingContent createSeminaryHomeListingContent(int parentId, String culture, String language) {
		
		SeminaryHomeListingContent pageContent = new SeminaryHomeListingContent();
		
		try {
			
			Category parentCategory = semDao.findCategoryById(parentId);
			
			// We set common parent 
			CategoryCoreContent commonParent = new CategoryCoreContent();
			commonParent.setId(parentCategory.getId());
			commonParent.setName(parentCategory.getName().getTextContentTranslationEntries().get(0).getTcteTranslation());
			commonParent.setDescription(parentCategory.getDescription().getTextContentTranslationEntries().get(0).getTcteTranslation());
			pageContent.setCommonParent(commonParent);
			
			for (int i = 0; i < 10; i++) {
				
				SeminaryCoreContent generatedContent = new SeminaryCoreContent();
				generatedContent.setId(i);
				generatedContent.setTitle("Autogenerated Seminar");
				
				generatedContent.setAuthor("Marc-André Beaudry");
				generatedContent.setLastEditor("Marc-André Beaudry");
				generatedContent.setDifficulty("HARD");
				
				generatedContent.setCreatedDate("2013-06-06");
				generatedContent.setEditedDate("2013-06-06");
				
				pageContent.getSeminariesChildren().add(generatedContent);
			}
			
		} catch (Exception e) {
			// TODO: handle exception
		}		
		
		return pageContent;
	}	
}
