package educatus.shared.services.requestservice;

public enum RequestTypeEnum {
	MAIN_PAGE_CONTENT_REQUEST,
	FOOTER_CONTENT_REQUEST,	
	HOME_PAGE_CONTENT_REQUEST,
	
	SEMINARY_HOME_PAGE_CATEGORY_CONTENT_REQUEST,
	SEMINARY_HOME_PAGE_LISTING_CONTENT_REQUEST,
	SEMINARY_EDITOR_CONTENT_REQUEST,
	SEMINARY_VIEWER_CONTENT_REQUEST,
	SEMINARY_CONTENT_REQUEST,
	
	PROFIL_PAGE_CONTENT_REQUEST
}
