package educatus.shared.services.requestservice;

public enum RequestTypeEnum {
	LOGIN_REQUEST,
	
	MAIN_PAGE_CONTENT_REQUEST,
	HOME_PAGE_CONTENT_REQUEST,
	
	SEMINARY_HOME_PAGE_CATEGORY_CONTENT_REQUEST,
	SEMINARY_HOME_PAGE_LISTING_CONTENT_REQUEST,	
	SEMINARY_CONTENT_REQUEST,
	
	SEMINARY_ADMINISTRATION_CONTENT_REQUEST,
	CATEGORY_ADMINISTRATION_CONTENT_REQUEST,
	
	SEMINARY_ADMINISTRATION_ACTION_REQUEST,
	
	PROFIL_PAGE_CONTENT_REQUEST
}
