package educatus.shared.services.requestservice;

public enum ResponseTypeEnum {	
	/* Page Content Responses */
	MAIN_PAGE_CONTENT_RESPONSE,
	HOME_PAGE_CONTENT_RESPONSE,
	PROFIL_PAGE_CONTENT_RESPONSE,
	SEMINARY_ADMINISTRATION_PAGE_CONTENT_RESPONSE,
	CATEGORY_ADMINISTRATION_PAGE_CONTENT_RESPONSE,
	EXERCICE_ADMINISTRATION_PAGE_CONTENT_RESPONSE,
	
	LOGIN_RESPONSE,
	USER_LISTING_RESPONSE,
	USER_CONTENT_RESPONSE,

	SEMINARY_HOME_PAGE_CATEGORY_CONTENT_RESPONSE,
	SEMINARY_HOME_PAGE_LISTING_CONTENT_RESPONSE,
	EXERCICE_HOME_PAGE_LISTING_CONTENT_RESPONSE,
	SEMINARY_CONTENT_RESPONSE,
	
	EXERCICE_CONTENT_RESPONSE,
	EXERCICE_QUESTION_VALIDATION_RESPONSE,
	
	
	SEMINARY_ADMINISTRATION_ACTION_RESPONSE,
	EXERCICE_ADMINISTRATION_ACTION_RESPONSE
}
