package educatus.shared.services.requestservice;

public enum ResponseTypeEnum {
	MAIN_MENU_CONTENT_RESPONSE,
	FOOTER_CONTENT_RESPONSE,
	
	HOME_PAGE_CONTENT_RESPONSE,
	SEMINARY_HOME_PAGE_CATEGORY_CONTENT_RESPONSE,
	SEMINARY_HOME_PAGE_LISTING_CONTENT_RESPONSE,
	SEMINARY_EDITOR_CONTENT_RESPONSE,
	SEMINARY_VIEWER_CONTENT_RESPONSE,
	PROFIL_PAGE_CONTENT_RESPONSE
}
